Add: status input value  to notify-mattermost-feed-deployment.yml (#26)

diff --git a/.github/workflows/notify-mattermost-feed-deployment.yml b/.github/workflows/notify-mattermost-feed-deployment.yml
--- a/.github/workflows/notify-mattermost-feed-deployment.yml
+++ b/.github/workflows/notify-mattermost-feed-deployment.yml
@@ -4,13 +4,21 @@ on:
   workflow_call:
     inputs:
       commit:
-        description: "The commit used by the github checkout action."
+        description: "The commit used by the github checkout action. Default: main branch"
         type: string
-        required: true
+        default: "main"
+      exit-with-status:
+        description: "Exit this job/workflow with the monitored job status. Options: true or false. Default: true"
+        type: string
+        default: "true"
       highlight:
         description: "Mattermost highlight. Default: devops"
         type: string
         default: "devops"
+      status:
+        description: "The monitored job, job status."
+        type: string
+        required: true
     secrets:
       MATTERMOST_FEED_BOT_WEBHOOK_URL:
         required: true
@@ -22,6 +30,7 @@ jobs:
     runs-on:
       - self-hosted
       - self-hosted-generic
+    if: ${{ !cancelled() }} && ( inputs.status == 'failure' || inputs.status == 'success' )
     steps:
       - name: Notify Mattermost Feed Deployment
         uses: greenbone/actions/mattermost-notify@v3
@@ -33,3 +42,9 @@ jobs:
           commit: ${{ inputs.commit }}
           workflow: ${{ github.run_id }}
           workflow-name: ${{ github.workflow }}
+          status: ${{ inputs.status }}
+      - name: Exit with monitored job status
+        if: inputs.exit-with-status == 'true' && inputs.status != 'success'
+        run: |
+          echo "Monitored job failed. Exit job/workflow with failure"
+          exit 1
